### ISSUE TITLE
ValueError: total size of new array must be unchanged

### ISSUE THREAD

**Issue by suishii** [DenisTome/Lifting-from-the-Deep-release#28]
Hello, I try to use the demo.py to get results but for some pictures, it give me the error as show as below.
How can I fix it? 
Expect your answer.

Traceback (most recent call last):
  File "demo.py", line 89, in <module>
    sys.exit(main())
  File "demo.py", line 54, in main
    pose_2d, visibility, pose_3d = pose_estimator.estimate(image)
  File "/home/suiishii/Lifting-from-the-Deep-release/packages/lifting/_pose_estimator.py", line 144, in estimate
    pose_3d = self.poseLifting.compute_3d(transformed_pose2d, weights)
  File "/home/suiishii/Lifting-from-the-Deep-release/packages/lifting/utils/prob_model.py", line 256, in compute_3d
    norm_pose, _ = Prob3dPose.normalise_data(reg_joints, weights)
  File "/home/suiishii/Lifting-from-the-Deep-release/packages/lifting/utils/prob_model.py", line 107, in normalise_data
    d2 = d2.reshape(d2.shape[0], -1, 2).transpose(0, 2, 1)
ValueError: total size of new array must be unchanged

**Comment by DenisTome** [comment]
The reason of that error is that all the people identified in your images have an uncertainty lower than a certain threshold.
In order to solve the problem, you can change such threshold in the file packages/lifting/utils/config.py by setting ```VISIBLE_PART = 1e-3``` to a lower value.

**Comment by suishii** [comment]
I see! 
Thank you very much.
