### ISSUE TITLE
 ValueError: total size of new array must be unchanged

### ISSUE THREAD

**Issue by suishii** [DenisTome/Lifting-from-the-Deep-release#29]
I met an issue when I run the demo.py file. For some pictures, it works, but for some pictures, it gave an error.
How can I fix it?
Expect your answer!

Traceback (most recent call last):
  File "demo1.py", line 68, in <module>
    sys.exit(main())
  File "demo1.py", line 40, in main
    pose_2d, visibility, pose_3d = pose_estimator.estimate(image)
  File "/home/suiishii/Lifting-from-the-Deep-release/packages/lifting/_pose_estimator.py", line 144, in estimate
    pose_3d = self.poseLifting.compute_3d(transformed_pose2d, weights)
  File "/home/suiishii/Lifting-from-the-Deep-release/packages/lifting/utils/prob_model.py", line 256, in compute_3d
    norm_pose, _ = Prob3dPose.normalise_data(reg_joints, weights)
  File "/home/suiishii/Lifting-from-the-Deep-release/packages/lifting/utils/prob_model.py", line 107, in normalise_data
    d2 = d2.reshape(d2.shape[0], -1, 2).transpose(0, 2, 1)
ValueError: total size of new array must be unchanged

**Comment by DenisTome** [comment]
I've already replied to you problem here: #28
